SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- USUÁRIO

CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

-- CONTA

CREATE TABLE IF NOT EXISTS `mydb`.`CONTA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_usuario` INT NOT NULL,
  `Nome_da_conta` VARCHAR(50) NOT NULL,
  `Saldo` DECIMAL(10,2) NOT NULL,
  `Tipo_de_conta` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`, `ID_usuario`),
  INDEX `fk_CONTA_USUARIO_idx` (`ID_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_CONTA_USUARIO`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `mydb`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- CATEGORIA

CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

-- DESPESAS

CREATE TABLE IF NOT EXISTS `mydb`.`DESPESAS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `Detalhes` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

-- RECEITAS

CREATE TABLE IF NOT EXISTS `mydb`.`RECEITAS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `Detalhes` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

-- TRANSAÇÕES

CREATE TABLE IF NOT EXISTS `mydb`.`TRANSACAO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_conta` INT NOT NULL,
  `Valor` DECIMAL(10,2) NOT NULL,
  `Data` DATETIME NOT NULL,
  `Tipo` VARCHAR(20) NOT NULL,
  `ID_categoria` INT NOT NULL,
  `ID_despesa` INT NULL,
  `ID_receita` INT NULL,
  PRIMARY KEY (`ID`, `ID_conta`, `ID_categoria`),
  INDEX `fk_TRANSACAO_CONTA1_idx` (`ID_conta` ASC) VISIBLE,
  INDEX `fk_TRANSACAO_CATEGORIA1_idx` (`ID_categoria` ASC) VISIBLE,
  INDEX `fk_TRANSACAO_DESPESAS1_idx` (`ID_despesa` ASC) VISIBLE,
  INDEX `fk_TRANSACAO_RECEITAS1_idx` (`ID_receita` ASC) VISIBLE,
  UNIQUE INDEX `ID_despesa_UNIQUE` (`ID_despesa` ASC) VISIBLE,
  UNIQUE INDEX `ID_receita_UNIQUE` (`ID_receita` ASC) VISIBLE,
  CONSTRAINT `fk_TRANSACAO_CONTA1`
    FOREIGN KEY (`ID_conta`)
    REFERENCES `mydb`.`CONTA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACAO_CATEGORIA1`
    FOREIGN KEY (`ID_categoria`)
    REFERENCES `mydb`.`CATEGORIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACAO_DESPESAS1`
    FOREIGN KEY (`ID_despesa`)
    REFERENCES `mydb`.`DESPESAS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACAO_RECEITAS1`
    FOREIGN KEY (`ID_receita`)
    REFERENCES `mydb`.`RECEITAS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;